### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by aseyboldt** [conda-forge/seqan-library-feedstock#1]
For some reason it says "build disabled" for the windows version.
@patricksnape any idear?

**Comment by ocefpaf** [comment]
Because the Windows builds are disable in the `meta.yaml`. See https://github.com/conda-forge/seqan-library-feedstock/blob/master/recipe/meta.yaml#L16

**Comment by aseyboldt** [comment]
Shouldn't that only disable the python2.7 version on windows?

**Comment by ocefpaf** [comment]
> Shouldn't that only disable the python2.7 version on windows?

If so it is not working: http://anaconda.org/conda-forge/seqan-library/files

Try re-rendering with `conda-smithy` and check if the `appveyor.yml` is created. Maybe there is a bug in the feedstock creation :confused: 

To re-render you have to install `conda-smithy` and then type `conda smithy rerender` from the root directory of the feedstock. Then commit the changes in a PR.

**Comment by patricksnape** [comment]
That seems like feedstock creation failed? It definitely [ran on Appveyor](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.7187).

**Comment by aseyboldt** [comment]
rerendering doesn't help. This seems related:
https://github.com/conda-forge/conda-smithy/issues/257
It's not a big problem for this repo, I can enable builds for all python versions on Windows when https://github.com/seqan/seqan/issues/1856 is fixed.
